trigger:
- main  # or any branch you want to monitor

pool:
  name: Default  # your local Windows agent pool

variables:
  imageName: 'dotnetapp'                         # your Docker image name
  acrLoginServer: 'mycompanyacr212.azurecr.io'  # your ACR login server
  tag: '$(Build.BuildId)'                       # auto-tag with build ID

steps:
# Optional: Checkout your repo
- checkout: self

# Build & Push Docker Image to ACR
- task: Docker@2
  displayName: Build and Push Image to ACR
  inputs:
    containerRegistry: 'acr-service-conn'     # must match service connection name
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)
      latest

# Publish a dummy artifact to trigger CD pipeline
- task: PublishBuildArtifacts@1
  displayName: Publish dummy artifact to trigger release
  inputs:
    PathtoPublish: 'README.md'     # or any small file
    ArtifactName: 'drop'
    publishLocation: 'Container'